name: Build Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - run: |
          cd frontend
          pnpm install
          pnpm run build
