name: Test Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - run: |
          pnpm install -r
          cd api
          pnpm run dev &
          cd ..
          pnpm run test:run
